### PR TITLE
Fix #5 and add tests for touch functionality

### LINKED ISSUE #5: Mouse dragging is broken on touch-capable devices
On my touch-enabled laptop running the latest Chrome, touch dragging works but mouse dragging doesn't. PR #6 contains my suggested fix.

### PR DESCRIPTION
**Pull request by motiz88**
In this PR, I have:
* Removed the globals `root` and `bodyElement` in favor of always setting and clearing events on `this.getDOMNode().ownerDocument.body`.
* Removed `isTouchDevice` and the either/or relationship between touch and mouse events in favor of tracking the source device on a per-drag basis. This tracking relies on having separate handlers for touch and mouse events; For the record, my earlier approach of just inspecting `event.type` in the shared handlers did not pan out, because `TestUtils.Simulate` doesn't seem to set that property.
* Removed `dragEventFor` in favor of `dragEventsFor.mouse` and `dragEventsFor.touch`.
* Changed the semantics of `state.dragging` slightly - its value is now always one of  `false`, `'touch'` and `'mouse'`. This is mainly so that a stray `mouseup` doesn't interfere with an ongoing touch-based drag operation, and vice versa.
* Added tests that use simulated touch events alongside the existing ones for mouse events. (All tests pass on my machine, but please see #7)

### CODE REVIEW

File: lib/draggable.js [hunk 1]
```diff
@@ -435,11 +428,42 @@ module.exports = React.createClass({
...
+    return this.handleDragStart(e, 'mouse');
+  },
+
+  handleMouseMove: function(e) {
+    return this.handleDrag(e, 'mouse');
   },
 
-  handleDragStart: function (e) {
+  handleMouseUp: function(e) {
+    return this.handleDragEnd(e, 'mouse');
```
Comment (mikepb) [inline lib/draggable.js]: Would it make sense to add `e.preventDefault()` here too?
http://www.html5rocks.com/en/mobile/touchandmouse/

Comment (motiz88) [inline lib/draggable.js]: Yes, absolutely, just ran into that myself. (Though in that case the `preventDefault` line should probably just move to `handleDrag`)
